site-1  | Migrations for 'app':
site-1  |   app/migrations/0001_initial.py
site-1  |     + Create model User
site-1  |     + Create model Channel
site-1  |     + Create model ChannelUser
site-1  |     + Create model Game
site-1  |     + Create model Message
site-1  |     + Create model Messages
site-1  |     + Create model Tournament
site-1  |     + Create model TournamentGame
site-1  |     + Create model TournamentPlayer
site-1  | Operations to perform:
site-1  |   Apply all migrations: account, admin, app, auth, contenttypes, sessions, socialaccount
site-1  | Running migrations:
site-1  |   Applying contenttypes.0001_initial... OK
site-1  |   Applying contenttypes.0002_remove_content_type_name... OK
site-1  |   Applying auth.0001_initial... OK
site-1  |   Applying auth.0002_alter_permission_name_max_length... OK
site-1  |   Applying auth.0003_alter_user_email_max_length... OK
site-1  |   Applying auth.0004_alter_user_username_opts... OK
site-1  |   Applying auth.0005_alter_user_last_login_null... OK
site-1  |   Applying auth.0006_require_contenttypes_0002... OK
site-1  |   Applying auth.0007_alter_validators_add_error_messages... OK
site-1  |   Applying auth.0008_alter_user_username_max_length... OK
site-1  |   Applying auth.0009_alter_user_last_name_max_length... OK
site-1  |   Applying auth.0010_alter_group_name_max_length... OK
site-1  |   Applying auth.0011_update_proxy_permissions... OK
site-1  |   Applying auth.0012_alter_user_first_name_max_length... OK
site-1  |   Applying app.0001_initial... OK
site-1  |   Applying account.0001_initial... OK
site-1  |   Applying account.0002_email_max_length... OK
site-1  |   Applying account.0003_alter_emailaddress_create_unique_verified_email... OK
site-1  |   Applying account.0004_alter_emailaddress_drop_unique_email... OK
site-1  |   Applying account.0005_emailaddress_idx_upper_email... OK
site-1  |   Applying account.0006_emailaddress_lower... OK
site-1  |   Applying account.0007_emailaddress_idx_email... OK
site-1  |   Applying account.0008_emailaddress_unique_primary_email_fixup... OK
site-1  |   Applying account.0009_emailaddress_unique_primary_email... OK
site-1  |   Applying admin.0001_initial... OK
site-1  |   Applying admin.0002_logentry_remove_auto_add... OK
site-1  |   Applying admin.0003_logentry_add_action_flag_choices... OK
site-1  |   Applying sessions.0001_initial... OK
site-1  |   Applying socialaccount.0001_initial... OK
site-1  |   Applying socialaccount.0002_token_max_lengths... OK
site-1  |   Applying socialaccount.0003_extra_data_default_dict... OK
site-1  |   Applying socialaccount.0004_app_provider_id_settings... OK
site-1  |   Applying socialaccount.0005_socialtoken_nullable_app... OK
site-1  |   Applying socialaccount.0006_alter_socialaccount_extra_data... OK
site-1  | Superuser created successfully.
site-1  | Superuser created successfully.
site-1  | INFO:     Will watch for changes in these directories: ['/app']
site-1  | INFO:     Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
site-1  | INFO:     Started reloader process [10] using WatchFiles
site-1  | INFO:     Started server process [12]
site-1  | INFO:     Waiting for application startup.
site-1  | INFO:     ASGI 'lifespan' protocol appears unsupported.
site-1  | INFO:     Application startup complete.
site-1  | INFO:     172.18.0.1:46226 - "GET /ProfilePage/ HTTP/1.1" 302 Found
site-1  | INFO:     172.18.0.1:46226 - "GET /SignIn/?next=/ProfilePage/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:46226 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | /usr/local/lib/python3.10/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
site-1  |   warnings.warn(
site-1  | INFO:     172.18.0.1:46242 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46238 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/icons/google-icon.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46242 - "GET /static/icons/favicon.ico HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:46226 - "POST /SignIn/ HTTP/1.1" 302 Found
site-1  | INFO:     172.18.0.1:46226 - "GET /ProfilePage/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:46226 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46242 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46238 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46252 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/css/profilepage.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46242 - "GET /static/js/profile.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/icons/edit-pp.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/fonts/Hoskin.otf HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 46262) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:46226 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:46226 - "GET / HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:46242 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46252 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46238 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/js/bgGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46226 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:46266 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 46274) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:46226 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60582 - "GET /ProfilePage/ HTTP/1.1" 302 Found
site-1  | INFO:     172.18.0.1:60582 - "GET /SignIn/?next=/ProfilePage/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60582 - "GET /static/js/index.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60588 - "GET /static/css/chatbox.css HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60616 - "GET /static/css/index.css HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60582 - "GET /static/icons/favicon.ico HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60616 - "GET /static/icons/google-icon.svg HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60616 - "GET /static/images/bg-text.svg HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60582 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60626 - "POST /SignIn/ HTTP/1.1" 302 Found
site-1  | INFO:     172.18.0.1:60626 - "GET /ProfilePage/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60626 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60640 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60654 - "GET /static/js/chatScript.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60668 - "GET /static/css/profilepage.css HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60642 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60674 - "GET /static/js/profile.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60626 - "GET /static/icons/edit-pp.svg HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60654 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60626 - "GET /static/icons/arrow-left.png HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60654 - "GET /static/fonts/Hoskin.otf HTTP/1.1" 200 OK
site-1  | INFO:     ('172.18.0.1', 60690) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:60654 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:54966 - "GET / HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:54966 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54972 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54978 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54966 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54972 - "GET /static/js/bgGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54978 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54980 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 54994) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:54972 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60654 - "GET / HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60668 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60640 - "GET /static/js/bgGame.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60654 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60674 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60626 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60654 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60626 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 54996) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:60654 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60654 - "GET /GameModes/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60674 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60668 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60654 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60626 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60640 - "GET /static/js/main.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60626 - "GET /static/js/field.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60674 - "GET /static/js/ball.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60654 - "GET /static/js/OnlineGame.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60668 - "GET /static/js/player.js HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:60626 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60654 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:60654 - "GET /static/js/Game.js HTTP/1.1" 200 OK
site-1  | INFO:     ('172.18.0.1', 55006) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:60654 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:54966 - "GET /GameModes/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:54972 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54980 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54978 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54966 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54972 - "GET /static/js/main.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54972 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:55014 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54978 - "GET /static/js/field.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54980 - "GET /static/js/player.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54972 - "GET /static/js/OnlineGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:55014 - "GET /static/js/ball.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:54972 - "GET /static/js/Game.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 55028) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:54972 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | admin (1)
site-1  | INFO:     172.18.0.1:35820 - "GET /AIMode/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:35820 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35832 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35834 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35850 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35832 - "GET /static/js/AIMode.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35850 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35840 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35834 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35832 - "GET /static/js/Launcher.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 35852) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     172.18.0.1:35834 - "GET /static/js/OnlineGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35840 - "GET /static/js/Game.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35850 - "GET /static/js/field.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:35832 - "GET /static/js/player.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35834 - "GET /static/js/ball.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35840 - "GET /static/js/AI.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35850 - "GET /static/js/TimerGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35820 - "GET /static/js/RushGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35832 - "GET /static/js/MaxScoreGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 35868) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:35834 - "GET /static/js/TimerMode.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35864 - "GET /static/images/Player1.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35840 - "GET /static/images/Player2.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35850 - "GET /static/images/Ball.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:35832 - "GET /navbar/ HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:33334 - "GET / HTTP/1.1" 200 OK
site-1  | INFO:     172.18.0.1:33334 - "GET /static/css/chatbox.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:33344 - "GET /static/css/index.css HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:33334 - "GET /static/js/chatScript.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:33344 - "GET /static/js/bgGame.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:33356 - "GET /static/js/index.js HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:33368 - "GET /static/images/bg-text.svg HTTP/1.1" 304 Not Modified
site-1  | INFO:     172.18.0.1:33344 - "GET /static/icons/arrow-left.png HTTP/1.1" 304 Not Modified
site-1  | INFO:     ('172.18.0.1', 33370) - "WebSocket /wss/chatbox/" [accepted]
site-1  | INFO:     connection open
site-1  | ERROR:    Exception in ASGI application
site-1  | Traceback (most recent call last):
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
site-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
site-1  |     return await self.app(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
site-1  |     return await application(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
site-1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
site-1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
site-1  |     return await super().__call__(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
site-1  |     return await self.inner(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
site-1  |     return await application(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
site-1  |     return await consumer(scope, receive, send)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
site-1  |     await await_many_dispatch(
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/utils.py", line 51, in await_many_dispatch
site-1  |     await dispatch(result)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
site-1  |     await handler(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
site-1  |     await self.connect()
site-1  |   File "/app/app/consumers.py", line 608, in connect
site-1  |     await self.accept()
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/generic/websocket.py", line 186, in accept
site-1  |     await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/consumer.py", line 81, in send
site-1  |     await self.base_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/channels/sessions.py", line 226, in send
site-1  |     return await self.real_send(message)
site-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 342, in asgi_send
site-1  |     raise RuntimeError(msg % message_type)
site-1  | RuntimeError: Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.
site-1  | INFO:     connection closed
site-1  | INFO:     172.18.0.1:33356 - "GET /navbar/ HTTP/1.1" 200 OK
